### ISSUE TITLE
Better histograms with equiprobale cells

### ISSUE THREAD

**Issue by r-radloff** [skuschel/generatorpipeline#19]
When chosing the width of histogram cells the use of equiprobale cells is advantageous over the use of equal-size cells as it ensures a better representation of the underlying distribution (see paragraph 6 of the paper of [Jain and Chlamtac](https://dl.acm.org/doi/10.1145/4372.4378)).

A histogram with $b$ equiprobale cells makes use of $(b - 1)$ quantiles. The needed quantile, we could estimate using the  $P^2$-algorithm (Isssue #18).

**Comment by skuschel** [comment]
Use CDFEstimator class. Added in PR #30
